name: Build and deploy documentation
on:
  push:
    branches:
      - bugfix/pdoc

jobs:
  create_documentation:
    runs-on: ubuntu-latest
    name: Deploy documentation

    steps:

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install doxygen
        sudo apt-get install python3-pip python3-dev python3-numpy
        pip install -U pip setuptools
        pip install -U numpy
        pip install -U netCDF4
        pip install -U pdoc

    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: bufr

    - name: Build library and documentation
      run: |
        export CC=gcc-9
        export FC=gfortran-9
        cd bufr
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=./install -DENABLE_PYTHON=ON -DENABLE_DOCS=ON ..
        make -j2
        make install
        mv docs/html $GITHUB_WORKSPACE/docs

    - name: Deploy documentation
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: docs
