name: Build and deploy documentation
on:
  push:
    branches:
      - bugfix/pdoc
#      - develop replace above line after confirmation from owners

jobs:
  create_documentation:
    runs-on: ubuntu-latest
    name: Deploy documentation

    steps:

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install doxygen
        sudo apt-get install python3-pip python3-dev python3-numpy
        pip install -U pip setuptools
        pip install -U numpy
        pip install -U netCDF4
        pip install -U pdoc

    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: bufr

    - name: Build library and documentation
      run: |
        export CC=gcc-9
        export FC=gfortran-9
        cd bufr
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=./install -DENABLE_PYTHON=ON -DENABLE_DOCS=ON ..
        make -j2
        make install
        mv docs/html $GITHUB_WORKSPACE/docs

    - name: Build library and documentation
      run: |
        export CC=gcc-9
        export FC=gfortran-9
        cd bufr
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=./install -DENABLE_PYTHON=ON -DENABLE_DOCS=ON ..
        make -j2
        make install
        mv docs/html $GITHUB_WORKSPACE/docs
        cd $GITHUB_WORKSPACE
        ls -R docs/

# Disable until confirmation from owners
#    - name: Deploy documentation
# Disable until confirmation from owners
#    - name: Deploy documentation
#      uses: JamesIves/github-pages-deploy-action@4.1.4
#      with:
#        branch: gh-pages
#        folder: docs

# Remove after confirmation from owners
    - name: Upload documentation
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: docs
