# This is a GitHub CI workflow for the NCEPLIBS-bufr project.
#
# This workflow tests on MacOS.
#
# Ed Hartnett, 1/10/23
name: MacOS
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  MacOS:
    runs-on: macos-latest
    env:
      FC: gfortran-11
      F90: gfortran-11

    steps:

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    
    - name: install-deps
      run: |
        pip3 install numpy
        pip3 install meson
        pip3 install ninja
        pip3 install netCDF4
        pip3 install protobuf
          
    - name: checkout-bufr
      uses: actions/checkout@v4
      with: 
        path: bufr

    - name: cache-data
      id: cache-data
      uses: actions/cache@v4
      with:
        path: ~/data
        key: data-15

    - name: build-bufr
      run: |
        cd bufr
        mkdir build 
        cd build
        cmake -DTEST_FILE_DIR=/Users/runner/data -DCMAKE_INSTALL_PREFIX=./install -DENABLE_PYTHON=ON ..
        make -j2 VERBOSE=1
        make install

    - name: test-bufr
      run: |
        cd bufr/build
        ctest --verbose --output-on-failure --rerun-failed

    - name: cache-data
      if: steps.cache-data.outputs.cache-hit != 'true'
      run: |
        mkdir ~/data
        cp $GITHUB_WORKSPACE/bufr/build/test/bufr-12.1.0.tgz ~/data
