name: Python Build and Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        ccompiler: [gcc-10]
        fcompiler: [gfortran-10]
        
    steps:

    - name: install-deps
      run: |
        if [[ ${{ matrix.os }} == "ubuntu-20.04" ]]; then
          sudo apt-get update
          sudo apt-get install doxygen
          sudo apt-get install python3-pip python3-dev python3-numpy
          sudo python3 -m pip install -U pip setuptools
          sudo python3 -m pip install -U numpy
          sudo python3 -m pip install -U netCDF4
          sudo python3 -m pip install -U pdoc pytest
        fi

    - name: checkout
      uses: actions/checkout@v2
      with:
        path: bufr
        submodules: true

    - name: build
      run: |
        if [[ ${{ matrix.ccompiler }} == "gcc-10" ]]; then
          export CC=gcc-10
        fi
        if [[ ${{ matrix.fcompiler }} == "gfortran-10" ]]; then
          export FC=gfortran-10
        fi
        cd bufr
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=./install -DENABLE_PYTHON=ON ..
        make -j2
        cd python
        make install

    - name: test
      run: |
        cd $GITHUB_WORKSPACE/bufr/build
        ctest --output-on-failure
