name: Build and Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      FC: gfortran-9
      CC: gcc-9

    steps:

    - name: install-deps
      run: |
        sudo apt-get update
        sudo apt-get install doxygen
        sudo apt-get install python3-pip python3-dev python3-numpy
        sudo python3 -m pip install -U pip setuptools
        sudo python3 -m pip install -U numpy
        sudo python3 -m pip install -U netCDF4
        sudo python3 -m pip install -U pdoc

    - name: checkout
      uses: actions/checkout@v2
      with:
        path: bufr
        submodules: true

    - name: build
      run: |
        cd bufr
        mkdir build
        cd build
        cmake ..
        make -j2

    - name: test
      run: |
        cd $GITHUB_WORKSPACE/bufr/build
        ctest
